# Generated by Django 6.0.6 on 2026-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password_1', models.CharField(max_length=255)),
                ('password_2', models.CharField(max_length=255)),
            ],
        ),
    ]
