# Generated by Django 6.0.6 on 2026-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(default='Bot', max_length=255),
        ),
    ]
